import { env } from "cloudflare:workers";
import { asc, eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { apiIntegrations, crmAuditLog } from "../../../../db/schema";
import { getChatGPTUser } from "../../../chatgpt-auth";

async function admin() { return await getChatGPTUser() ?? (process.env.NODE_ENV !== "production" ? { email: "local-admin@yazrestaurant.co.uk" } : null); }
async function ensureTable(){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS api_integrations (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, provider text NOT NULL, label text NOT NULL, base_url text DEFAULT '' NOT NULL, secret_encrypted text NOT NULL, secret_hint text DEFAULT '' NOT NULL, enabled integer DEFAULT true NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();}
async function encryptionKey() { const runtime=env as unknown as Record<string,unknown>; const source=String(runtime.API_ENCRYPTION_KEY??process.env.API_ENCRYPTION_KEY??(process.env.NODE_ENV!=="production"?"yaz-local-development-key-change-before-production":"")); if(!source)throw new Error("API_ENCRYPTION_KEY is not configured"); return crypto.subtle.importKey("raw",await crypto.subtle.digest("SHA-256",new TextEncoder().encode(source)),"AES-GCM",false,["encrypt"]); }
async function encrypt(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},await encryptionKey(),new TextEncoder().encode(value)));return `${Buffer.from(iv).toString("base64")}.${Buffer.from(encrypted).toString("base64")}`;}
const publicRow=(row:typeof apiIntegrations.$inferSelect)=>({id:row.id,provider:row.provider,label:row.label,baseUrl:row.baseUrl,secretHint:row.secretHint,enabled:row.enabled,updatedAt:row.updatedAt});

export async function GET(){if(!await admin())return Response.json({error:"Unauthorised"},{status:401});await ensureTable();const rows=await getDb().select().from(apiIntegrations).orderBy(asc(apiIntegrations.label));return Response.json({integrations:rows.map(publicRow)});}
export async function POST(request:Request){const user=await admin();if(!user)return Response.json({error:"Unauthorised"},{status:401});const body=await request.json() as Record<string,unknown>;const provider=String(body.provider??"custom").trim().slice(0,60),label=String(body.label??"").trim().slice(0,120),secret=String(body.secret??"").trim(),baseUrl=String(body.baseUrl??"").trim().slice(0,500);if(!label||secret.length<4||secret.length>8000)return Response.json({error:"Name and API key are required"},{status:400});if(baseUrl&&!/^https:\/\//i.test(baseUrl))return Response.json({error:"Base URL must use HTTPS"},{status:400});const [row]=await getDb().insert(apiIntegrations).values({provider,label,baseUrl,secretEncrypted:await encrypt(secret),secretHint:secret.slice(-4),enabled:body.enabled!==false}).returning();await getDb().insert(crmAuditLog).values({actorEmail:user.email,action:"integration.created",detail:`${provider}: ${label}`});return Response.json({integration:publicRow(row)},{status:201});}
export async function PATCH(request:Request){const user=await admin();if(!user)return Response.json({error:"Unauthorised"},{status:401});const body=await request.json() as Record<string,unknown>,id=Number(body.id);if(!id)return Response.json({error:"Invalid id"},{status:400});const baseUrl=String(body.baseUrl??"").trim().slice(0,500);if(baseUrl&&!/^https:\/\//i.test(baseUrl))return Response.json({error:"Base URL must use HTTPS"},{status:400});const values:Partial<typeof apiIntegrations.$inferInsert>={label:String(body.label??"").trim().slice(0,120),provider:String(body.provider??"custom").slice(0,60),baseUrl,enabled:body.enabled!==false,updatedAt:new Date().toISOString()};const secret=String(body.secret??"").trim();if(secret){values.secretEncrypted=await encrypt(secret);values.secretHint=secret.slice(-4);}await getDb().update(apiIntegrations).set(values).where(eq(apiIntegrations.id,id));await getDb().insert(crmAuditLog).values({actorEmail:user.email,action:"integration.updated",detail:`Integration ${id}`});return Response.json({ok:true});}
export async function DELETE(request:Request){const user=await admin();if(!user)return Response.json({error:"Unauthorised"},{status:401});const id=Number(new URL(request.url).searchParams.get("id"));if(!id)return Response.json({error:"Invalid id"},{status:400});await getDb().delete(apiIntegrations).where(eq(apiIntegrations.id,id));await getDb().insert(crmAuditLog).values({actorEmail:user.email,action:"integration.deleted",detail:`Integration ${id}`});return Response.json({ok:true});}
