import { requestHasAdminSession } from "../../../../lib/admin-auth";
import { encryptIntegrationSecret, nextId, readAdminStore, writeAdminStore } from "../../../../lib/local-admin-store";

function denied(request:Request){return !requestHasAdminSession(request)}
function publicIntegration(item:Awaited<ReturnType<typeof readAdminStore>>["integrations"][number]){const {secretEncrypted:_,...safe}=item;return safe}
function validSecret(provider:string,value:string){if(provider==="google-analytics")return /^G-[A-Z0-9]+$/i.test(value);if(provider==="google-ads"){try{const config=JSON.parse(value);return /^AW-\d+$/i.test(config.id)&&Boolean(config.lead)}catch{return false}}if(provider==="google-tag-manager")return /^GTM-[A-Z0-9]+$/i.test(value);if(provider==="google-maps")return /^AIza[A-Za-z0-9_-]{20,}$/.test(value);if(provider==="opentable")return /^\d{4,}$/.test(value);if(provider==="meta")return /^\d{8,20}$/.test(value);return false}
export async function GET(request:Request){if(denied(request))return Response.json({error:"Unauthorised"},{status:401});const store=await readAdminStore();return Response.json({integrations:store.integrations.map(publicIntegration)})}
export async function POST(request:Request){if(denied(request))return Response.json({error:"Unauthorised"},{status:401});const body=await request.json();const provider=String(body.provider??""),secret=String(body.secret??"").trim(),label=String(body.label??"").trim();if(!secret||!label)return Response.json({error:"Connection name and service ID are required"},{status:400});if(!validSecret(provider,secret))return Response.json({error:"Check the service ID format and required Google Ads lead conversion label"},{status:400});const store=await readAdminStore(),now=new Date().toISOString();store.integrations.push({id:nextId(store.integrations),provider,label,baseUrl:String(body.baseUrl??""),secretEncrypted:encryptIntegrationSecret(secret),secretHint:secret.slice(-4),enabled:body.enabled!==false,createdAt:now,updatedAt:now});await writeAdminStore(store);return Response.json({ok:true},{status:201})}
export async function PATCH(request:Request){if(denied(request))return Response.json({error:"Unauthorised"},{status:401});const body=await request.json(),store=await readAdminStore(),item=store.integrations.find(entry=>entry.id===Number(body.id));if(!item)return Response.json({error:"Integration not found"},{status:404});item.provider=String(body.provider??item.provider);item.label=String(body.label??item.label).trim();item.baseUrl=String(body.baseUrl??item.baseUrl);item.enabled=body.enabled!==false;const secret=String(body.secret??"").trim();if(secret){if(!validSecret(item.provider,secret))return Response.json({error:"Check the service ID format and required Google Ads lead conversion label"},{status:400});item.secretEncrypted=encryptIntegrationSecret(secret);item.secretHint=secret.slice(-4)}item.updatedAt=new Date().toISOString();await writeAdminStore(store);return Response.json({ok:true})}
export async function DELETE(request:Request){if(denied(request))return Response.json({error:"Unauthorised"},{status:401});const id=Number(new URL(request.url).searchParams.get("id")),store=await readAdminStore();store.integrations=store.integrations.filter(item=>item.id!==id);await writeAdminStore(store);return Response.json({ok:true})}
