"use client";
import { upload } from "@vercel/blob/client";
import { FormEvent,useEffect,useState } from "react";
import type { MediaSettings } from "../../lib/media";

const fields:{key:keyof MediaSettings;label:string;kind:"image"|"video";help:string}[]=[
 {key:"logoImage",label:"Restaurant logo",kind:"image",help:"Used in the website header and footer. PNG, WebP or SVG with a transparent background works best."},
 {key:"heroVideo",label:"Homepage hero video",kind:"video",help:"The full-screen video at the top of the homepage."},
 {key:"duetVideo",label:"Story section video",kind:"video",help:"The arched video in the From our kitchen section."},
 {key:"heroImage",label:"Hero fallback image",kind:"image",help:"Shown while the hero video loads and on reduced-motion devices."},
 {key:"foodImage",label:"Food fallback image",kind:"image",help:"Shown while the story video loads."},
];
export function MediaManager(){
 const[password,setPassword]=useState("");const[settings,setSettings]=useState<MediaSettings|null>(null);const[notice,setNotice]=useState("");const[busy,setBusy]=useState<string|null>(null);const[authChecked,setAuthChecked]=useState(false);
 async function loadSettings(){const response=await fetch("/api/admin/media",{cache:"no-store"});const result=await response.json();if(response.ok){setSettings(result.settings);if(!result.storageReady)setNotice("Connect Vercel Blob before uploading or saving media.")}else if(response.status!==401)setNotice(result.error??"Could not load media")}
 useEffect(()=>{fetch("/api/admin/session").then(response=>response.json()).then(result=>{if(result.authenticated)loadSettings()}).finally(()=>setAuthChecked(true))},[]);
 async function signIn(event:FormEvent){event.preventDefault();setBusy("login");setNotice("");const response=await fetch("/api/admin/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const result=await response.json();setBusy(null);if(!response.ok)return setNotice(result.error??"Could not sign in");setPassword("");await loadSettings()}
 async function chooseFile(key:keyof MediaSettings,file:File|undefined){if(!file||!settings)return;setBusy(key);setNotice(`Uploading ${file.name}...`);try{let url="";if(location.hostname==="localhost"){const data=new FormData();data.set("file",file);const response=await fetch("/api/admin/media/local-upload",{method:"POST",body:data}),result=await response.json();if(!response.ok)throw new Error(result.error??"Upload failed");url=result.url}else{const blob=await upload(`yaz-media/${key}/${file.name}`,file,{access:"public",handleUploadUrl:"/api/admin/media/upload"});url=blob.url}setSettings({...settings,[key]:url});setNotice("Upload complete. Select Save all changes.")}catch(error){setNotice(error instanceof Error?error.message:"Upload failed")}setBusy(null)}
 async function save(){if(!settings)return;setBusy("save");setNotice("");const response=await fetch("/api/admin/media",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});const result=await response.json();setBusy(null);setNotice(response.ok?"Saved successfully.":result.error??"Could not save")}
 if(!authChecked)return <main className="media-login"><p>Checking admin session…</p></main>;
 if(!settings)return <main className="media-login"><form onSubmit={signIn}><a className="admin-brand" href="/"><span>Y</span>AZ<small>CONTROL</small></a><p className="eyebrow">Secure website management</p><h1>Media library</h1><p>Sign in to change the videos and images used across the website.</p><label>Admin password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} required autoComplete="current-password"/></label><button disabled={busy==="login"}>{busy?"Signing in...":"Open media library"}</button><span className="media-notice" aria-live="polite">{notice}</span></form></main>;
 return <main className="media-admin"><header><div><a className="admin-brand" href="/admin"><span>Y</span>AZ<small>CONTROL</small></a><p className="eyebrow">Website management</p><h1>Logo, videos &amp; images</h1><p>Upload new media or paste an HTTPS URL. Save to update the local preview.</p></div><a href="/admin">Back to control</a></header><section className="media-grid">{fields.map(field=><article key={field.key}><div className={`media-preview ${field.kind}`}>{field.kind==="video"?<video src={settings[field.key]} muted loop autoPlay playsInline/>:settings[field.key]?<img src={settings[field.key]} alt=""/>:<span className="media-placeholder">No logo yet</span>}</div><div className="media-copy"><span>{field.kind}</span><h2>{field.label}</h2><p>{field.help}</p><label className="upload-button">{busy===field.key?"Uploading...":"Choose file"}<input type="file" accept={field.kind==="video"?"video/mp4,video/webm":"image/jpeg,image/png,image/webp,image/avif,image/svg+xml"} disabled={busy!==null} onChange={event=>chooseFile(field.key,event.target.files?.[0])}/></label><label className="media-url">Media URL<input type="text" value={settings[field.key]} onChange={event=>setSettings({...settings,[field.key]:event.target.value})}/></label></div></article>)}</section><footer className="media-save"><span aria-live="polite">{notice}</span><button onClick={save} disabled={busy!==null}>{busy==="save"?"Saving...":"Save all changes"}</button></footer></main>
}
