import type { Metadata } from "next";
import { asc } from "drizzle-orm";
import { getDb } from "../../db";
import { siteRecords } from "../../db/schema";

export const metadata:Metadata={title:"Turkish & Mediterranean Menu in Highams Park | Yaz",description:"Explore charcoal grills, colourful meze, seafood and vegetarian dishes at Yaz Restaurant in Highams Park, London.",alternates:{canonical:"/menu"},openGraph:{title:"Yaz Restaurant Menu | Highams Park",description:"Turkish and Mediterranean dishes made for sharing, from relaxed brunch to dinner.",url:"/menu"}};
export const dynamic="force-dynamic";
const fallback=[{title:"Yaz Mixed Grill",subtitle:"",body:"Charcoal-grilled lamb, chicken, adana, rice and house salad"},{title:"Mediterranean Sea Bass",subtitle:"",body:"Herbs, lemon, seasonal greens and olive oil"},{title:"Anatolian Meze",subtitle:"",body:"A generous table of vibrant dips, warm bread and shared plates"}];
export default async function MenuPage(){let menu=fallback;try{const rows=await getDb().select().from(siteRecords).orderBy(asc(siteRecords.position));const live=rows.filter(r=>r.type==="menu"&&r.active);if(live.length)menu=live;}catch{}return <main className="seo-page"><header className="seo-nav"><a className="brand" href="/"><span>Y</span>AZ</a><nav><a href="/">Home</a><a href="/private-hire">Private hire</a><a href="/#visit">Visit</a></nav><a className="header-book" href="/#book">Book a table</a></header><section className="seo-hero"><p className="eyebrow">Turkish &amp; Mediterranean dining · Highams Park</p><h1>The Yaz menu</h1><p>Generous plates, charcoal-fired favourites and bright Mediterranean flavours, served seven days a week in East London.</p></section><section className="seo-content"><div className="seo-heading"><p className="eyebrow dark">A taste of Yaz</p><h2>Made for the whole table.</h2><p>Our kitchen brings together Anatolian recipes and modern Mediterranean cooking. Vegetarian choices and halal dishes are available throughout the menu; please tell the team about allergies before ordering.</p></div><div className="menu-list">{menu.map((item,index)=><article key={item.title}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{item.title}{item.subtitle&&<b className="menu-price">{item.subtitle}</b>}</h3><p>{item.body}</p></div></article>)}</div><div className="seo-cta"><h2>Ready to join us?</h2><p>Find Yaz at 7–9 Signal Walk, Highams Park, London E4 9BW.</p><a className="button button-gold" href="/#book">Reserve with OpenTable</a></div></section></main>}
